Feat/create transaction
Alcancia-io/Alcancia-nest-graphql pull request #37
Opened 2022-09-26 15:16 UTC by Royer99

- [x] Create transaction
- [x] Update transaction status

2022-09-26 18:56 UTC, pellerano commented
Royer si el feature no esta listo para merge ni para review no tienes que abrir el PR😂

2022-10-12 00:31 UTC, pellerano approved these changes
LGTM 🚀

2022-10-12 01:25 UTC, juandatorr99 requested changes
Hacer enums el status de la transacción

2022-10-12 01:25 UTC, juandatorr99 commented on src/transactions/transactions.service.ts
> +        1,
Este es el status? Si es asi hay que cambiarlo por un enum como habiamos hablado

2022-10-19 00:24 UTC, pellerano commented on src/transactions/transactions.service.ts
> +        1,
Done 👍🏼

2022-10-19 00:24 UTC, Royer99 commented on src/transactions/transactions.service.ts
> +        1,
OK, ya lo cambiamos a enum

2022-10-19 01:26 UTC, juandatorr99 approved these changes
Nice one

2022-10-19 22:40 UTC, merged