Feature/oink 878 humanizar notificaciones, OINK-871, OINK-872, OINK-873
Alcancia-io/Alcancia-nest-graphql pull request #70
Opened 2023-01-31 23:49 UTC by DHurtado714-itesm

Notifications have been implemented. Both push notifications and Whatsapp notifications in Metamap, Suarmi and CP.

2023-01-31 23:49 UTC, juandatorr99 commented
Task linked: [OINK-878 Humanizar las notifications](https://app.clickup.com/t/24497898/OINK-878)

2023-01-31 23:49 UTC, juandatorr99 commented
Task linked: [OINK-871 Whatsapp notifiction cuando se complete el KYC](https://app.clickup.com/t/24497898/OINK-871)

2023-01-31 23:49 UTC, juandatorr99 commented
Task linked: [OINK-872 Whatsapp notifiction cuando se complete una orden (Deposito o retiro)](https://app.clickup.com/t/24497898/OINK-872)

2023-01-31 23:49 UTC, juandatorr99 commented
Task linked: [OINK-873 Push notification cuando se complete el KYC](https://app.clickup.com/t/24497898/OINK-873)

2023-02-01 00:15 UTC, pellerano requested changes
No haz hecho rebase. Corre:

`git fetch && git rebase origin/develop` 

Te sugiero que lo hagas para que puedas resolver cualquier conflicto que tengas que no se este viendo a simple vista.

2023-02-01 02:41 UTC, DHurtado714-itesm commented
ya le hice rebase y comparandolo desde el github, se pueden ver que la rama no tiene ningun cambio pendiente de develop.

2023-02-01 02:57 UTC, pellerano requested changes
Resolver errores con numeros de RD.

2023-02-01 03:11 UTC, pellerano requested changes
Needs some work, but overall good 👍🏼

2023-02-01 03:11 UTC, pellerano commented on src/cryptopay/cryptopay.service.ts
> +      currentStatus = status === 'COMPLETED' ? '1' : status == 'FAILED' ? '0' : status == 'PENDING' ? '2' : null;
Esto deberia ser `currentStatus = status === 'COMPLETED' ? '1' : status == 'FAILED' ? '0' : '2'`

2023-02-01 03:11 UTC, pellerano commented on src/suarmi/suarmi.service.ts
> +      currentStatus = status === 'COMPLETED' ? '1' : status == 'FAILED' ? '0' : status == 'PENDING' ? '2' : null;
Esto tambien debe ser `currentStatus = status === 'COMPLETED' ? '1' : status == 'FAILED' ? '0' :  '2'`

2023-02-01 03:11 UTC, pellerano commented on src/utils/whatsappNotification.ts
> +      phone = '521' + phone.split('+52')[1];
Esto tambien te va a dar error con los numeros de RD.

2023-02-01 03:14 UTC, DHurtado714-itesm commented on src/utils/whatsappNotification.ts
> +      phone = '521' + phone.split('+52')[1];
Para RD también es necesario añadirle un 1 después del código del país?

2023-02-01 03:15 UTC, DHurtado714-itesm commented on src/cryptopay/cryptopay.service.ts
> +      currentStatus = status === 'COMPLETED' ? '1' : status == 'FAILED' ? '0' : status == 'PENDING' ? '2' : null;
Claro pelle tienes razón hago el cambio

2023-02-01 03:17 UTC, pellerano commented on src/utils/whatsappNotification.ts
> +      phone = '521' + phone.split('+52')[1];
Sip

2023-02-01 03:34 UTC, DHurtado714-itesm commented on src/utils/whatsappNotification.ts
> +      phone = '521' + phone.split('+52')[1];
#Ok, sugieres algún cambió, no logro ver en donde cometí el error. Pienso yo que ese condicional ve si el número es de Mexico y le agrega el 1, pero claro que puedo estar mal.

2023-02-01 04:00 UTC, pellerano commented on src/utils/whatsappNotification.ts
> +      phone = '521' + phone.split('+52')[1];
Bueno primero tienes que saber si el numero es de RD o de MX y obvio tienes que hacerlo de una manera que se puedan verificar numeros de otros paises que queramos enviarle notificaciones en el futuro.

Ya con lo que tienes en la linea 8, si le estas agregando el 1 pero tambien le agregas el 52 antes de ese 1, por ejemplo:
Si tengo el numero '+524461098903' ese split lo que va a hacer es retorna '4461098903' y despues seteas la variable de phone como '521' + lo que te retorna el split (4461098903) lo cual te resulta en '524461098903'.  Entonces si le pasas un numero de RD a ese split te va a retornar error pq los numeros de RD no tienen '+52'.

2023-02-01 22:51 UTC, DHurtado714-itesm commented on src/utils/whatsappNotification.ts
> +    if (phone.split('+52')[1].length !== 10) throw new Error('Invalid phone number');
si claro ya vi este error, ese caso solo funcionaria con los numeros de mexico. Tienes razon pelle, ya lo quite porque eso se verifica en el login

2023-02-01 22:54 UTC, DHurtado714-itesm commented on src/utils/whatsappNotification.ts
> +      phone = '521' + phone.split('+52')[1];
Pruebalo de nuevo y me dices si los cambios que hice estan bien. Lo que veo es que si el numero es de RD, no se le hace el split, al unico que se le hace es al mexicano.

2023-02-03 19:40 UTC, pellerano approved these changes
LGTM! 🚀

2023-02-03 22:03 UTC, merged