Feature/oink 898 withdraw notification
Alcancia-io/Alcancia-nest-graphql pull request #76
Opened 2023-03-08 23:49 UTC by DHurtado714-itesm

Feature/OIN 854 Resolve Dependencies Vulnerabilities, included

2023-03-08 23:49 UTC, juandatorr99 commented
Task linked: [OINK-898 Withdraw notification](https://app.clickup.com/t/24497898/OINK-898)

2023-03-10 00:51 UTC, pellerano requested changes

2023-03-10 00:51 UTC, pellerano commented on src/notifications/notifications.service.ts
> +      } else if (currentStatus === 'VERIFIED') {
currentStatus es un string o un number? Segun la db es un int pero en el back es un enum de TransactionStatus, tonces cual es? pq estas usando tanto `'0'` como `'VERIFIED'` cual de los dos es?

2023-03-10 00:54 UTC, DHurtado714-itesm commented on src/notifications/notifications.service.ts
> +      } else if (currentStatus === 'VERIFIED') {
En transaction es un int pero en KYC es un string

` private async updateUserVerified(uid: string, status: string) {
    const [user, error] = await catchResult(this.usersService.findOne(uid));
    if (error || !user) throw new ApolloError(`${error}`);
    let currentStatus: string;
    currentStatus = status === 'reviewNeeded' ? 'PENDING' : status === 'rejected' ? 'FAILED' : status.toUpperCase();
    const [userSaved, userSavedError] = await catchResult(
      this.userRepository.update(uid, { ...user, kycStatus: currentStatus })
    );
    if (userSavedError || !userSaved) throw new ApolloError(`${userSavedError}`);
    const { phoneNumber, deviceToken } = user;
    await this.notificationService.sendMetamapNotification(phoneNumber, deviceToken, currentStatus);

    return;`

2023-03-10 14:10 UTC, pellerano commented on src/notifications/notifications.service.ts
> +      } else if (currentStatus === 'VERIFIED') {
Ok es un string, pero en la linea 120 validas si currentStatus es `'VERIFIED'` y en la linea 109 y 113 validas si currentStatus es `'0'` o `'2'`, entonces a eso era que me referia que cual de los dos es? pq estoy seguro que no son los dos.

2023-03-17 05:01 UTC, pellerano approved these changes
LGTM!

2023-03-17 16:50 UTC, merged